name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: quickbite-backend/frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd quickbite-backend/frontend
        npm ci
    
    - name: Build React App
      run: |
        cd quickbite-backend/frontend
        npm run build
      env:
        REACT_APP_API_URL: https://quickbite-demo-backend.onrender.com/api
        REACT_APP_DEMO_MODE: true
        REACT_APP_FALLBACK_MODE: true
        GENERATE_SOURCEMAP: false
        CI: false
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: quickbite-backend/frontend/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4